export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_NEXT_PRODUCTS = "GET_NEXT_PRODUCTS";
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";